language:
 - c

before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -y dosemu

before_script:
 - . $OWROOT/cmnvars.sh

script:
 - sh $OWROOT/build.sh

after_failure:
 - mkdir -p $HOME/github/bld
 - cp bld/*.log $HOME/github/bld/
 - cd $HOME
 - git config --global user.email "travis@travis-ci.org"
 - git config --global user.name "Travis"
 - git clone --quiet --branch=master https://${GITHUB_TOKEN}@github.com/open-watcom/travis-ci-ow-builds.git
 - cd travis-ci-ow-builds.git
 - cp -Rf $HOME/github/* .
 - git add -f .
 - git commit -m "Travis build $TRAVIS_BUILD_NUMBER pushed to travis-ci-ow-builds"
 - git push -fq origin travis-ci-ow-builds
