language:
 - c

before_install:
# install latest OS fixes
 - sudo apt-get -qq update
# install DOSEMU
 - sudo apt-get install -y dosemu
# setup DOSEMU to work with OW build
 - sudo sysctl -w vm.mmap_min_addr=0
 - echo " \$_layout = \"us\"" > ~/.dosemurc

before_script:
# initialize OW build environment variables
 - . $OWROOT/cmnvars.sh

script:
# build fresh wmake tool
 - mkdir -p $OWSRCDIR/wmake/$OWOBJDIR
 - cd $OWSRCDIR/wmake/$OWOBJDIR
 - make -f ../posmake TARGETDEF=-D__LINUX__
# build fresh builder tool
 - mkdir -p $OWSRCDIR/builder/$OWOBJDIR
 - cd $OWSRCDIR/builder/$OWOBJDIR
 - $OWBINDIR/wmake -f ../binmake bootstrap=1 builder.exe
# build bootstrap tools
 - cd $OWSRCDIR
 - builder $OWBUILDEROPTS boot
# build OW distribution
 - builder $OWBUILDEROPTS build

after_failure:
# after failure transfer log files back to GitHub repository
 - cd $HOME
# configure Git
 - git config --global user.email "travis@travis-ci.org"
 - git config --global user.name "Travis CI"
 - git config --global push.default simple
# clone GitHub repository
 - git clone --quiet --branch=master https://${GITHUB_TOKEN}@github.com/open-watcom/travis-ci-ow-builds.git
# copy new log files to git repository tree
 - cd travis-ci-ow-builds
 - if [ ! -d bld ]; then mkdir bld; fi
 - if [ ! -d docs ]; then mkdir docs; fi
 - cp $OWROOT/bld/*.log bld/
 - cp $OWROOT/docs/*.log docs/
# commit new log files to GitHub repository
 - git add -f .
 - git commit -m "Travis CI build $TRAVIS_BUILD_NUMBER - log files"
 - git push -f origin
