language:
 - c

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y dosemu xfonts-dosemu xfonts-terminus-dos

before_script:
 - . $OWROOT/cmnvars.sh

script:
 - sh $OWROOT/build.sh

