language: c

addons:
  apt:
    packages:
      # install DOS Emulator
      - dosemu
      # install Ghostscript
      - ghostscript

before_script:
 # get clone of GitHub repository to return Travis CI OW build/log files
 # and compress GitHub repository if necessary to hold only a few last builds
 - sh travis/gitget.sh
 # initialize OW build environment variables
 - export OWROOT=$TRAVIS_BUILD_DIR
 - export OWRELROOT=$TRAVIS_BUILD_DIR/../travis-ci-ow-builds
 - export OWOBJDIR=binbuild
 - export OWDOCBUILD=0
 - export OWDOCQUIET=1
 - export USE_FILENAME_VERSION=1
 - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then export BUILDER_OPT=-q; fi
 - . cmnvars.sh
 - env | sed -n -e '/^TRAVIS/p' -e '/^OW/p' | sort

#script:
# - sh build.sh rel

after_failure:
 # after failure transfer log files back to GitHub repository
 - sh travis/gitupdf.sh

after_success:
 # after success transfer OW build to GitHub repository
 - sh travis/gitupds.sh

jobs:
  include:
    - stage: Bootstrap Linux
      os: linux
      compiler: clang
      sudo: required
      env:
        - OWTOOLS=CLANG
        - OWDOCBUILD=0
        - OWVERBOSE=1
        - OWTRAVISJOB=BOOTLINUX
      script: sh travis/build.sh boot
      before_cache:
        # upload OW build tools
        - sh travis/savtools.sh
    - stage: Build Linux
      os: linux
      compiler: clang
      sudo: required
      env:
        - OWTOOLS=CLANG
        - OWDOCBUILD=0
        - OWVERBOSE=0
        - OWTRAVISJOB=BUILDLINUX
      install:
        # download OW build tools
        - sh travis/rsttools.sh
      script: sh travis/build.sh rel
    - stage: Build PDF documentation
      os: linux
      compiler: clang
      sudo: required
      env:
        - OWTOOLS=CLANG
        - OWDOCBUILD=1
        - OWVERBOSE=0
        - OWTRAVISJOB=PDFDOCLINUX
        - OWGHOSTSCRIPTPATH=$PATH
      install:
        # download OW build tools
        - sh travis/rsttools.sh
      script: sh travis/build.sh docpdf
    - stage: Bootstrap OSX
      os: osx
      compiler: clang
      env:
        - OWTOOLS=CLANG
        - OWDOCBUILD=0
        - OWVERBOSE=1
        - OWTRAVISJOB=BOOTOSX
      script: sh travis/build.sh boot
      before_cache:
        # upload OW build tools
        - sh travis/savtools.sh
    - stage: Build OSX
      os: osx
      compiler: clang
      env:
        - OWTOOLS=CLANG
        - OWDOCBUILD=0
        - OWVERBOSE=0
        - OWTRAVISJOB=BUILDOSX
      install:
        # install DOS Emulator
        - brew install dosbox
        - export OWDOSBOX=dosbox
        # install Ghostscript
        - brew install ghostscript
        # download OW build tools
        - sh travis/rsttools.sh
      script: sh travis/build.sh rel

#addons:
#  coverity_scan:
#    project:
#      name: "open-watcom/open-watcom-v2"
#      description: "Build submitted via Travis CI"

#    notification_email:    malak.jiri@gmail.com
#    build_command_prepend:
#    build_command:         $OWROOT/build.sh
#    branch_pattern:        master
