language: c

compiler: clang

sudo: false

env:
  global:
    - OWROOT=$TRAVIS_BUILD_DIR
    - OWTOOLS=CLANG
    - OWOBJDIR=binbuild
    - OWDOCBUILD=0
    - OWDOCQUIET=1
    - USE_FILENAME_VERSION=1

addons:
  apt:
    packages:
      # install DOS Emulator
      - dosemu
      # install Ghostscript
      - ghostscript

cache:
  directories:
    - build/bin
    - bld/watcom/binbuild

before_script:
 # initialize OW build environment variables
 - . travis/setowenv.sh
 # get clone of GitHub repository to return Travis CI OW build/log files
 # and compress GitHub repository if necessary to hold only a few last builds
 - travis/gitget.sh
 - env | sed -n -e '/^TRAVIS/p' -e '/^OW/p' | sort

#script:
# - build.sh rel

after_failure:
 # after failure transfer log files back to GitHub repository
 - travis/gitupdf.sh

after_success:
 # after success transfer OW build to GitHub repository
 - travis/gitupds.sh

jobs:
  include:
    #################################
    - stage: Bootstrap
      os: linux
      install:
        - export OWTRAVISJOB=BOOTSTRAP
        - export OWDOCBUILD=0
        - export OWVERBOSE=1
      script: travis/build.sh boot
    - # ...
      os: osx
      install:
        - export OWTRAVISJOB=BOOTSTRAP
        - export OWDOCBUILD=0
        - export OWVERBOSE=1
      script: travis/build.sh boot
    #################################
    - stage: Build
      os: linux
      install:
        - export OWTRAVISJOB=BUILD
        - export OWDOCBUILD=0
        - export OWVERBOSE=0
        - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then export BUILDER_OPT=-q; fi
      script: travis/build.sh rel
    - # ...
      os: osx
      install:
        - export OWTRAVISJOB=BUILD
        - export OWDOCBUILD=0
        - export OWVERBOSE=0
        - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then export BUILDER_OPT=-q; fi
        # install DOS Emulator
        - brew install dosbox
        - export OWDOSBOX=dosbox
        # install Ghostscript
        - brew install ghostscript
      script: travis/build.sh rel
    #################################
    - stage: PDF Documentation
      os: linux
      install:
        - export OWTRAVISJOB=DOCPDF
        - export OWDOCBUILD=1
        - export OWVERBOSE=0
        - export OWGHOSTSCRIPTPATH=$PATH
      script: travis/build.sh docpdf
    #################################
    - stage: Clear cache
      os: linux
      install: export OWTRAVISJOB=CLEARCACHE
      before_script: true
      script: travis/clrcache.sh
    - # ...
      os: osx
      install: export OWTRAVISJOB=CLEARCACHE
      before_script: true
      script: travis/clrcache.sh

#addons:
#  coverity_scan:
#    project:
#      name: "open-watcom/open-watcom-v2"
#      description: "Build submitted via Travis CI"

#    notification_email:    malak.jiri@gmail.com
#    build_command_prepend:
#    build_command:         $OWROOT/build.sh
#    branch_pattern:        master
