language: c

cache: ccache
  directories:
    - build/bin

addons:
  apt:
    packages:
      - dosemu

before_script:
# get clone of GitHub repository to return Travis CI OW build/log files
# and compress GitHub repository if necessary to hold only a few last builds
 - sh travis/gitget.sh
# initialize OW build environment variables
 - export OWROOT=$TRAVIS_BUILD_DIR
 - export OWRELROOT=$TRAVIS_BUILD_DIR/../travis-ci-ow-builds
 - export OWOBJDIR=binbuild
 - export OWDOCBUILD=0
 - export OWDOCQUIET=1
 - export USE_FILENAME_VERSION=1
 - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then export BUILDER_OPT=-q; fi
 - . cmnvars.sh

#script:
# - sh build.sh rel

after_failure:
# after failure transfer log files back to GitHub repository
 - sh travis/gitupdf.sh

after_success:
# after success transfer OW build to GitHub repository
 - sh travis/gitupds.sh

jobs:
  include:
    - stage: bootstrap_osx
      os: osx
      compiler: clang
      env: 
        - OWTOOLS=CLANG
        - OWDOCBUILD=0
        - OWVERBOSE=1
      install:
        # install ccache
        - brew install ccache
        - PATH=$PATH:/usr/local/opt/ccache/libexec
      script: sh travis/build.sh boot
    - stage: bootstrap_linux
      os: osx
      compiler: clang
      env: 
        - OWTOOLS=CLANG
        - OWDOCBUILD=0
        - OWVERBOSE=1
      script: sh travis/build.sh boot
    - stage: build_osx
      os: osx
      compiler: clang
      env: 
        - OWTOOLS=CLANG
        - OWDOCBUILD=0
        - OWVERBOSE=0
      install:
        # install ccache
        - brew install ccache
        - PATH=$PATH:/usr/local/opt/ccache/libexec
        # install DOS Emulator
        - brew install dosbox
        - export OWDOSBOX=dosbox
      script: sh travis/build.sh rel
    - stage: build_linux
      os: linux
      compiler: clang
      env: 
        - OWTOOLS=CLANG
        - OWDOCBUILD=0
        - OWVERBOSE=0
      script: sh travis/build.sh rel
    - stage: build_docs_pdf
      os: linux
      compiler: clang
      env: 
        - OWTOOLS=CLANG
        - OWDOCBUILD=1
        - OWVERBOSE=0
      script: sh travis/build.sh docpdf

#addons:
#  coverity_scan:
#    project:
#      name: "open-watcom/open-watcom-v2"
#      description: "Build submitted via Travis CI"

#    notification_email:    malak.jiri@gmail.com
#    build_command_prepend:
#    build_command:         $OWROOT/build.sh
#    branch_pattern:        master
