language: c

compiler: clang

sudo: required

env:
  global:
    - OWROOT=$TRAVIS_BUILD_DIR
    - OWTOOLS=CLANG
    - OWOBJDIR=binbuild
    - OWDOCBUILD=0
    - OWDOCQUIET=1
    - OWUSE_FILENAME_VERSION=1
    - GITQUIET=--quiet
    - COVERITY_VERBOSE=1

addons:
  apt:
    packages:
        # install C cache
      - ccache
        # install DOS Emulator
      - dosemu
        # install Ghostscript
      - ghostscript

cache:
  ccache: false
  directories:
    - build/bin
    - bld/watcom/binbuild

before_install:
 - export OWTRAVIS_REPO_SLUG=open-watcom/travis-ci-ow-builds
 - export OWTRAVIS_BUILD_DIR=${HOME}/build/$OWTRAVIS_REPO_SLUG
 - if [ "$OWTRAVIS_DEBUG" = "1" ]; then export GITQUIET=-v; fi

before_script:
   # initialize OW build environment variables
 - export OWRELROOT=$OWTRAVIS_BUILD_DIR
 - . ./cmnvars.sh
   # get clone of GitHub repository to return Travis CI OW build/log files
 - travis/gitget.sh
 - travis/envinfo.sh
 - travis/cacheinf.sh

#script:
# - build.sh rel

after_failure:
   # after failure transfer log files back to GitHub repository
 - travis/cacheinf.sh
 - travis/gitupdf.sh

after_success:
   # after success transfer OW build to GitHub repository
 - travis/cacheinf.sh
 - travis/gitupds.sh

jobs:
  allow_failures:
    - os: osx

  include:
    #################################
    - stage: Initialize
      os: linux
      before_script:
        - travis/envinfo.sh
        - travis/cacheinf.sh
      script: travis/tinit.sh
    #################################
    - stage: Bootstrap
      os: linux
      install:
        - export OWTRAVISJOB=BOOTSTRAP
        - export OWDOCBUILD=0
        - export OWVERBOSE=1
      script: travis/build.sh boot
    - # ...
      os: osx
      install:
        - export OWTRAVISJOB=BOOTSTRAP
        - export OWDOCBUILD=0
        - export OWVERBOSE=1
      script: travis/build.sh boot
    #################################
    - stage: Build
      os: linux
      addons:
        coverity_scan:
          project:
            name: "open-watcom/open-watcom-v2"
            description: "Build submitted via Travis CI"
            notification_email:    "malak.jiri@gmail.com"
            build_command_prepend:
            build_command:         "travis/build.sh scan"
            branch_pattern:        coverity_scan
      install:
        - export OWTRAVISJOB=BUILD
        - export OWDOCBUILD=0
        - export OWVERBOSE=0
        - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then export BUILDER_OPT=-q; fi
      script: travis/build.sh rel
    - # ...
      os: osx
      install:
        - export OWTRAVISJOB=BUILD
        - export OWDOCBUILD=0
        - export OWVERBOSE=0
        - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then export BUILDER_OPT=-q; fi
          # install C cache
        - brew install ccache
        - PATH=/usr/local/opt/ccache/libexec:$PATH
          # install DOS Emulator
        - brew install dosbox
        - export OWDOSBOX=dosbox
          # install Ghostscript
        - brew install ghostscript
      script: travis/build.sh rel
    #################################
    - stage: Documentation PDF
      os: linux
      install:
        - export OWTRAVISJOB=DOCPDF
        - export OWDOCBUILD=1
        - export OWVERBOSE=0
        - export OWGHOSTSCRIPTPATH=$PATH
      script: travis/build.sh docpdf
    #################################
    - stage: Finalize
      os: linux
      before_script:
        - travis/envinfo.sh
        - travis/cacheinf.sh
      script: travis/tfini.sh
    - # ...
      os: osx
      before_script:
        - travis/envinfo.sh
        - travis/cacheinf.sh
      script: travis/tfini.sh
