language: c

before_install:
# install DOS Emulator
 - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install dosbox; export OWDOSBOX=dosbox; fi

before_script:
# get clone of GitHub repository to return Travis CI OW build/log files
# and compress GitHub repository if necessary to hold only a few last builds
 - sh gitget.sh
# initialize OW build environment variables
 - export OWROOT=$TRAVIS_BUILD_DIR
 - export OWRELROOT=$TRAVIS_BUILD_DIR/../travis-ci-ow-builds
 - export OWOBJDIR=binbuild
 - export OWDOCBUILD=0
 - export OWDOCQUIET=1
 - export USE_FILENAME_VERSION=1
 - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then export BUILDER_OPT=-q; fi
 - . $OWROOT/cmnvars.sh

script:
 - sh $OWROOT/build.sh rel

after_failure:
# after failure transfer log files back to GitHub repository
 - sh gitupdf.sh

after_success:
# after success transfer OW build to GitHub repository
 - sh gitupds.sh

#addons:
#  coverity_scan:
#    project:
#      name: "open-watcom/open-watcom-v2"
#      description: "Build submitted via Travis CI"

#    notification_email:    malak.jiri@gmail.com
#    build_command_prepend:
#    build_command:         $OWROOT/build.sh
#    branch_pattern:        master

jobs:
  include:
    - stage: build_osx
      os: osx
      compiler: clang
      env: OWTOOLS=CLANG
      script: sh $OWROOT/build.sh rel
    - stage: build_linux
      os: linux
        addons:
          apt:
            packages:
              - dosemu
      compiler: clang
      env: OWTOOLS=CLANG
      script: sh $OWROOT/build.sh rel
    - stage: build_docs
      script: sh $OWROOT/build.sh docs
