language: c
dist: trusty
sudo: required
os: linux
compiler: gcc

git:
  depth: 3

env:
  global:
    - TRAVIS_TAG=Current-build
    - OWROOT=$TRAVIS_BUILD_DIR
    - OWOBJDIR=binbuild
    - OWVERBOSE=0
    - OWDISTRBUILD=0
    - OWDOCBUILD=0
    - OWDOCQUIET=1
    - OWBRANCH=master
    - OWBRANCH_DOCS=documentation
    - OWBRANCH_COVERITY=coverity_scan
    - OWBRANCH_SF=sourceforge
    - OWTRAVIS_BUILD_REPO_SLUG=open-watcom/travis-ci-ow-builds
    - OWTRAVIS_BUILD_DIR=${HOME}/build/$OWTRAVIS_BUILD_REPO_SLUG
    - OWTRAVIS_LOGS_REPO_SLUG=open-watcom/travis-ci-logs
    - OWTRAVIS_LOGS_DIR=${HOME}/build/$OWTRAVIS_LOGS_REPO_SLUG
    - OWRELROOT=$OWROOT/test
    - OWTRAVISDIR=$OWROOT/travis
    - OWDISTRDIR=$OWROOT/distrib
    - OWSRCDIR=$OWROOT/bld
    - OWBINDIR=$OWROOT/build/$OWOBJDIR
    - OWDOCSDIR=$OWROOT/docs
    - CP_OPTS=-Rnv

cache:
  directories:
    - build/$OWOBJDIR
    - bld/watcom/$OWOBJDIR
    - test
    - buildx

before_script:
 # configure Git client
 - git config --global user.email "openwatcomtravis@gmail.com"
 - git config --global user.name "Open Watcom Travis"
 - git config --global push.default simple
 # get environment/cache info if debug is active
 - $OWTRAVISDIR/envinfo.sh
 - $OWTRAVISDIR/cacheinf.sh

after_failure:
 # after failure transfer log files back to GitHub repository
 - $OWTRAVISDIR/cacheinf.sh
 - $OWTRAVISDIR/gitupdf.sh

after_success:
 # after success transfer OW build to GitHub repository
 - $OWTRAVISDIR/cacheinf.sh
 - $OWTRAVISDIR/gitupds.sh

jobs:
  allow_failures:
    - os: windows
  include:
    #################################
    - stage: Initialize
      name: "Initialize Travis GitHub repository and mirror master branch commits to SF"
      if: branch = env(OWBRANCH) AND type IN (push, cron)
      git:
        depth: false
      cache: false
      before_install:
        # stop unwanted services
        - $OWTRAVISDIR/services.sh
      script:
        # update SF mirror
        - $OWTRAVISDIR/gitusf.sh
    #################################
    - stage: Bootstrap
      name: "Build minimal set of build tools Linux"
      if: branch = env(OWBRANCH)
      before_install:
        # stop unwanted services
        - $OWTRAVISDIR/services.sh
        # set environmet variable
        - export OWTOOLS=GCC
        - export OWTRAVISJOB=BOOTSTRAP
        - export OWVERBOSE=1
        # clear cache
        - $OWTRAVISDIR/cacheclr.sh
      install:
        - . $OWROOT/cmnvars.sh
      script:
        - $OWTRAVISDIR/build.sh
    - # ...
      name: "Build minimal set of build tools OSX"
      if: branch = env(OWBRANCH) AND (type = cron)
      os: osx
      compiler: clang
      before_install:
        # stop unwanted services
        - $OWTRAVISDIR/services.sh
        # set environmet variable
        - export OWTOOLS=CLANG
        - export OWTRAVISJOB=BOOTSTRAP
        - export OWVERBOSE=1
        # clear cache
        - $OWTRAVISDIR/cacheclr.sh
      install:
        - . $OWROOT/cmnvars.sh
      script:
        - $OWTRAVISDIR/build.sh
    - # ...
      name: "Build minimal set of build tools Windows"
      if: branch = env(OWBRANCH) AND (type = cron)
      os: windows
      before_install:
        - test -n $CC && unset CC
        # stop unwanted services
        - $OWTRAVISDIR/services.sh
        # set environmet variable
        - export OWTOOLS=VISUALC
        - export OWTRAVISJOB=BOOTSTRAP
        - export OWVERBOSE=1
        # clear cache
        - $OWTRAVISDIR/cacheclr.sh
      install:
      script:
        - $OWTRAVISDIR/build.sh
    #################################
    - stage: Build
      name: "OW tools build Linux"
      if: branch = env(OWBRANCH)
      before_install:
        # stop unwanted services
        - $OWTRAVISDIR/services.sh
        # set environmet variable
        - export OWTOOLS=GCC
        - export OWTRAVISJOB=BUILD
      install:
        # install DOS Emulator
        - sudo apt-get install -y dosemu
        - . $OWROOT/cmnvars.sh
      script:
        - $OWTRAVISDIR/build.sh
      before_cache:
        - $OWTRAVISDIR/cache3.sh save
    - # ...
      name: "OW tools build-1 OSX"
      if: branch = env(OWBRANCH) AND (type = cron)
      os: osx
      compiler: clang
      before_install:
        # stop unwanted services
        - $OWTRAVISDIR/services.sh
        # set environmet variable
        - export OWTOOLS=CLANG
        - export OWTRAVISJOB=BUILD-1
      install:
        - . $OWROOT/cmnvars.sh
      script:
        - $OWTRAVISDIR/build.sh
      before_cache:
        - $OWTRAVISDIR/cache1.sh save
    - # ...
      name: "OW tools build-1 Windows"
      if: branch = env(OWBRANCH) AND (type = cron)
      os: windows
      before_install:
        - test -n $CC && unset CC
        # stop unwanted services
        - $OWTRAVISDIR/services.sh
        # set environmet variable
        - export OWTOOLS=VISUALC
        - export OWTRAVISJOB=BUILD-1
      install:
      script:
        - $OWTRAVISDIR/build.sh
      before_cache:
        - $OWTRAVISDIR/cache1.sh save
    #################################
    - stage: Build2
      name: "OW tools build-2 OSX"
      if: branch = env(OWBRANCH) AND (type = cron)
      os: osx
      compiler: clang
      before_install:
        # stop unwanted services
        - $OWTRAVISDIR/services.sh
        # set environmet variable
        - export OWTOOLS=CLANG
        - export OWTRAVISJOB=BUILD-2
        - export OWDOSBOX=dosbox
        - export SDL_VIDEODRIVER=dummy
      install:
        # install DOS Emulator
        - brew install dosbox
        - . $OWROOT/cmnvars.sh
      script:
        - $OWTRAVISDIR/cache1.sh load
        - $OWTRAVISDIR/build.sh
      before_cache:
        - $OWTRAVISDIR/cache2.sh save
    - # ...
      name: "OW tools build-2 Windows"
      if: branch = env(OWBRANCH) AND (type = cron)
      os: windows
      before_install:
        - test -n $CC && unset CC
        # stop unwanted services
        - $OWTRAVISDIR/services.sh
        # set environmet variable
        - export OWTOOLS=VISUALC
        - export OWTRAVISJOB=BUILD-2
      install:
      script:
        - $OWTRAVISDIR/cache1.sh load
        - $OWTRAVISDIR/build.sh
      before_cache:
        - $OWTRAVISDIR/cache2.sh save
    #################################
    - stage: Build3
      name: "OW tools build-3 OSX"
      if: branch = env(OWBRANCH) AND (type = cron)
      os: osx
      compiler: clang
      before_install:
        # stop unwanted services
        - $OWTRAVISDIR/services.sh
        # set environmet variable
        - export OWTOOLS=CLANG
        - export OWTRAVISJOB=BUILD-3
        - export OWDOSBOX=dosbox
        - export SDL_VIDEODRIVER=dummy
        - export OWDOCQUIET=0
        - export OWVERBOSE=1
      install:
        # install DOS Emulator
        - brew install dosbox
        - . $OWROOT/cmnvars.sh
      script:
        - $OWTRAVISDIR/cache2.sh load
        - $OWTRAVISDIR/build.sh
      before_cache:
        - $OWTRAVISDIR/cache3.sh save
    - # ...
      name: "OW tools build-3 Windows"
      if: branch = env(OWBRANCH) AND (type = cron)
      os: windows
      before_install:
        - test -n $CC && unset CC
        # stop unwanted services
        - $OWTRAVISDIR/services.sh
        # set environmet variable
        - export OWTOOLS=VISUALC
        - export OWTRAVISJOB=BUILD-3
        - export OWDOCQUIET=0
        - export OWVERBOSE=1
      install:
      script:
        - $OWTRAVISDIR/cache2.sh load
        - $OWTRAVISDIR/build.sh
      before_cache:
        - $OWTRAVISDIR/cache3.sh save
    #################################
    - stage: UpdateBuild
      name: "Update Build Linux"
      if: branch = env(OWBRANCH) AND (type = cron OR type = push)
      before_install:
        # stop unwanted services
        - $OWTRAVISDIR/services.sh
        # set environmet variable
        - export OWTOOLS=GCC
        - export OWTRAVISJOB=CPREL
      install:
#        - export WATCOM=$OWROOT/test
        - . $OWROOT/cmnvars.sh
      script:
#        - cp $CP_OPTS $OWROOT/buildx/ $WATCOM/
        - true
    - # ...
      name: "Update Build Windows"
      if: branch = env(OWBRANCH) AND (type = cron)
      os: windows
      before_install:
        # stop unwanted services
        - $OWTRAVISDIR/services.sh
        # set environmet variable
        - export OWTOOLS=VISUALC
        - export OWTRAVISJOB=CPREL
      install:
        - export WATCOM=$OWROOT/test
      script:
#        - cp $CP_OPTS $OWROOT/buildx/ $WATCOM
        - true
    #################################
#    - stage: InitTests
#      name: "Initialze Tests Environment"
#      if: branch = env(OWBRANCH) AND (type = cron)
#      before_install:
#        # stop unwanted services
#        - $OWTRAVISDIR/services.sh
#      install:
#        - export WATCOM=$OWROOT/test
#      script:
#        - cp $CP_OPTS $OWROOT/buildx/ $WATCOM/
    #################################
    - stage: Tests
      name: "Test wasm assembler"
      if: branch = env(OWBRANCH) AND (type = cron)
      before_install:
        # stop unwanted services
        - $OWTRAVISDIR/services.sh
        # set environmet variable
        - export OWTOOLS=WATCOM
        - export OWTRAVISJOB=TEST
        - export OWTRAVISTEST=WASM
      install:
        - export WATCOM=$OWROOT/test
        - export PATH=$WATCOM/binl:$PATH
        - export INCLUDE=$WATCOM/lh
        - unset LIB
        - . $OWROOT/cmnvars.sh
      script:
        - $OWTRAVISDIR/test.sh
    - # ...
      name: "Test C compiler"
      if: branch = env(OWBRANCH) AND (type = cron)
      before_install:
        # stop unwanted services
        - $OWTRAVISDIR/services.sh
        # set environmet variable
        - export OWTOOLS=WATCOM
        - export OWTRAVISJOB=TEST
        - export OWTRAVISTEST=C
      install:
        - export WATCOM=$OWROOT/test
        - export PATH=$WATCOM/binl:$PATH
        - export INCLUDE=$WATCOM/lh
        - unset LIB
        - . $OWROOT/cmnvars.sh
      script:
        - $OWTRAVISDIR/test.sh
    - # ...
      name: "Test FORTRAN 77 compiler"
      if: branch = env(OWBRANCH) AND (type = cron)
      before_install:
        # stop unwanted services
        - $OWTRAVISDIR/services.sh
        # set environmet variable
        - export OWTOOLS=WATCOM
        - export OWTRAVISJOB=TEST
        - export OWTRAVISTEST=F77
      install:
        - export WATCOM=$OWROOT/test
        - export PATH=$WATCOM/binl:$PATH
        - export INCLUDE=$WATCOM/lh
        - unset LIB
        - . $OWROOT/cmnvars.sh
      script:
        - $OWTRAVISDIR/test.sh
    - # ...
      name: "Test C++ compiler"
      if: branch = env(OWBRANCH) AND (type = cron)
      before_install:
        # stop unwanted services
        - $OWTRAVISDIR/services.sh
        # set environmet variable
        - export OWTOOLS=WATCOM
        - export OWTRAVISJOB=TEST
        - export OWTRAVISTEST=CXX
      install:
        - export WATCOM=$OWROOT/test
        - export PATH=$WATCOM/binl:$PATH
        - export INCLUDE=$WATCOM/lh
        - unset LIB
        - . $OWROOT/cmnvars.sh
      script:
        - $OWTRAVISDIR/test.sh
    - # ...
      name: "Test C run-time library"
      if: branch = env(OWBRANCH) AND (type = cron)
      before_install:
        # set environmet variable
        - export OWTOOLS=WATCOM
        - export OWTRAVISJOB=TEST
        - export OWTRAVISTEST=CRTL
      install:
        - export WATCOM=$OWROOT/test
        - export PATH=$WATCOM/binl:$PATH
        - export INCLUDE=$WATCOM/lh
        - unset LIB
        - . $OWROOT/cmnvars.sh
      script:
        - $OWTRAVISDIR/test.sh
    #################################
    - stage: Finalize
      name: "Delete build cache Linux"
      if: branch = env(OWBRANCH)
      script:
        - $OWTRAVISDIR/cacheclr.sh
    - # ...
      name: "Delete build cache OSX"
      if: branch = env(OWBRANCH) AND (type = cron)
      os: osx
      compiler: clang
      script:
        - $OWTRAVISDIR/cacheclr.sh
    - # ...
      name: "Delete build cache Windows"
      if: branch = env(OWBRANCH) AND (type = cron)
      os: windows
      script:
        - $OWTRAVISDIR/cacheclr.sh
    #################################
