#
# Pipeline for CI build and upload
#
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# specific files excluded
trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - relea-pl.yml
    - covsc-pl.yml
    - README.md

variables:
  owroot:           $(Build.SourcesDirectory)
  owobjdir:         binbuild
  owgitverbose:     -v

# owimage_lnx:      'ubuntu-18.04'
# owimage_nt:       'vs2017-win2016'
# owimage_osx:      'macOS-10.14'
  owimage_lnx:      'ubuntu-20.04'
  owimage_nt:       'windows-2019'
  owimage_osx:      'macOS-11'
  owscript_lnx:     ci/buildx.sh
  owscript_nt:      ci\buildx.cmd
  owscript_osx:     ci/buildx.sh
  owartifactfile:   owartifact.tar.xz
  owciroot_lnx:     $(owroot)/ci
  owciroot_nt:      $(owroot)\ci
  owciroot_osx:     $(owroot)/ci
  owcibin32:        $(owciroot_nt)\nt386
  owcibin64:        $(owciroot_nt)\ntx64

stages:
  - stage: start
    displayName: "Start"
    jobs:
      - job: start
        pool:
          vmImage: $(owimage_lnx)
        steps:
        - checkout: none
  - stage: bootosx
    displayName: "Bootstrap OSX"
    dependsOn:
      - start
    jobs:
      - template: ci/boot.yml
        parameters:
          arch:     osx
          title:    Bootstrap OSX
          owimage:  $(owimage_osx)
          owtools:  CLANG
          owscript: $(owscript_osx)
  - stage: buildosx
    displayName: "Build OSX"
    dependsOn:
      - bootosx
    jobs:
      - template: ci/build.yml
        parameters:
          arch:     osx
          title:    Build OSX
          owimage:  $(owimage_osx)
          owtools:  CLANG
          owscript: $(owscript_osx)
  - stage: bootlnxow
    displayName: "Bootstrap Linux OW"
    dependsOn:
      - start
    jobs:
      - template: ci/bootow.yml
        parameters:
          arch:     lnx
          title:    Bootstrap Linux OW
          owscript: $(owscript_lnx)
          owtools:  WATCOM
          owimage:  $(owimage_lnx)
  - stage: bootlnx
    displayName: "Bootstrap Linux"
    dependsOn:
      - start
    jobs:
      - template: ci/boot.yml
        parameters:
          arch:     lnx
          title:    Bootstrap Linux
          owimage:  $(owimage_lnx)
          owtools:  GCC
          owscript: $(owscript_lnx)
  - stage: buildlnx
    displayName: "Build Linux"
    dependsOn:
      - bootlnx
    jobs:
      - template: ci/build.yml
        parameters:
          arch:     lnx
          title:    Build Linux
          owimage:  $(owimage_lnx)
          owtools:  GCC
          owscript: $(owscript_lnx)
  - stage: bootntow
    displayName: "Bootstrap Windows OW"
    dependsOn:
      - start
    jobs:
      - template: ci/bootow.yml
        parameters:
          arch:     nt
          title:    Bootstrap Windows OW
          owscript: $(owscript_nt)
          owtools:  WATCOM
          owimage:  $(owimage_nt)
  - stage: bootnt
    displayName: "Bootstrap Windows"
    dependsOn:
      - start
    jobs:
      - template: ci/boot.yml
        parameters:
          arch:     nt
          title:    Bootstrap Windows
          owimage:  $(owimage_nt)
          owtools:  VISUALC
          owscript: $(owscript_nt)
  - stage: buildnt
    displayName: "Build Windows"
    dependsOn:
      - bootnt
    jobs:
      - template: ci/build.yml
        parameters:
          arch:     nt
          title:    Build Windows
          owimage:  $(owimage_nt)
          owtools:  VISUALC
          owscript: $(owscript_nt)
  - stage: docsnt
    displayName: "Docs Build Windows"
    dependsOn:
      - bootnt
    jobs:
      - template: ci/docs.yml
        parameters:
          arch:     nt
          title:    Documentation Build DOS
          doctype:  docdos
          owimage:  $(owimage_nt)
          owtools:  VISUALC
          owscript: $(owscript_nt)
      - template: ci/docs.yml
        parameters:
          arch:     nt
          title:    Documentation Build Html
          doctype:  dochtml
          owimage:  $(owimage_nt)
          owtools:  VISUALC
          owscript: $(owscript_nt)
      - template: ci/docs.yml
        parameters:
          arch:     nt
          title:    Documentation Build NT
          doctype:  docnt
          owimage:  $(owimage_nt)
          owtools:  VISUALC
          owscript: $(owscript_nt)
      - template: ci/docs.yml
        parameters:
          arch:     nt
          title:    Documentation Build OS2
          doctype:  docos2
          owimage:  $(owimage_nt)
          owtools:  VISUALC
          owscript: $(owscript_nt)
      - template: ci/docs.yml
        parameters:
          arch:     nt
          title:    Documentation Build PDF
          doctype:  docpdf
          owimage:  $(owimage_nt)
          owtools:  VISUALC
          owscript: $(owscript_nt)
      - template: ci/docs.yml
        parameters:
          arch:     nt
          title:    Documentation Build WIN
          doctype:  docwin
          owimage:  $(owimage_nt)
          owtools:  VISUALC
          owscript: $(owscript_nt)
  - stage: testslnx
    displayName: "Tests Linux"
    dependsOn:
      - buildlnx
    jobs:
      - template: ci/tests.yml
        parameters:
          arch:     lnx
          title:    Tests Linux
          owimage:  $(owimage_lnx)
          owtools:  GCC
          owscript: $(owscript_lnx)
  - stage: testbootlnxow
    displayName: "Test Bootstrap Linux OW"
    dependsOn:
      - testslnx
    jobs:
      - template: ci/testboot.yml
        parameters:
          arch:     lnx
          title:    Test Bootstrap Linux OW
          owimage:  $(owimage_lnx)
          owtools:  WATCOM
          owscript: $(owscript_lnx)
  - stage: testsnt
    displayName: "Tests Windows"
    dependsOn:
      - buildnt
    jobs:
      - template: ci/tests.yml
        parameters:
          arch:     nt
          title:    Tests Windows
          owimage:  $(owimage_nt)
          owtools:  VISUALC
          owscript: $(owscript_nt)
  - stage: testbootntow
    displayName: "Test Bootstrap Windows OW"
    dependsOn:
      - testsnt
    jobs:
      - template: ci/testboot.yml
        parameters:
          arch:     nt
          title:    Test Bootstrap Windows OW
          owimage:  $(owimage_nt)
          owtools:  WATCOM
          owscript: $(owscript_nt)
  - stage: lastbuild
    displayName: "Last CI build"
    dependsOn:
      - testbootlnxow
      - testbootntow
      - docsnt
    jobs:
      - template: ci/lastbld.yml
        parameters:
          title:    Last CI Build
