parameters:
  arch:     ''
  title:    ''

jobs:
  - job: boot${{ parameters.arch }}
    displayName: "${{ parameters.title }}"
    variables:
      ${{ if eq(parameters.arch, 'lnx') }}:
        owtools:      $(owtools_lnx)
        owtoolsv:     $(owtoolsv_lnx)
        owscript:     $(owscript_lnx)
      ${{ if eq(parameters.arch, 'nt') }}:
        owtools:      $(owtools_nt)
        owtoolsv:     $(owtoolsv_nt)
        owscript:     $(owscript_nt)
      ${{ if eq(parameters.arch, 'osx') }}:
        owtools:      $(owtools_osx)
        owtoolsv:     $(owtoolsv_osx)
        owscript:     $(owscript_osx)
      owbuild.stage:    boot
    pool:
      ${{ if eq(parameters.arch, 'lnx') }}:
        vmImage: $(owimage_lnx)
      ${{ if eq(parameters.arch, 'nt') }}:
        vmImage: $(owimage_nt)
      ${{ if eq(parameters.arch, 'osx') }}:
        vmImage: $(owimage_osx)
    steps:
    - ${{ if eq(parameters.arch, 'nt') }}:
      - script: |
          dir "C:\Program Files (x86)\Microsoft Visual Studio\"
          dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\"
          dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\"
          dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\"
          dir "C:\Program Files\Microsoft Visual Studio\2019\"
    - script: $(owscript)
      displayName: "Bootstrap"
    - template: artfsave.yml
      parameters:
        path:       build/$(owobjdir)
        artifname:  build-${{ parameters.arch }}
    - template: artfsave.yml
      parameters:
        path:       bld/watcom/$(owobjdir)
        artifname:  bld-watcom-${{ parameters.arch }}
