parameters:
  arch:     ''
  title:    ''
  owimage:  ''
  owtools:  ''
  owscript: ''

jobs:
  - job: boot${{ parameters.arch }}
    displayName: "${{ parameters.title }}"
    pool:
      vmImage: ${{ parameters.owimage }}
    steps:
    - script: ${{ parameters.owscript }}
      displayName:  "Bootstrap"
      env:
        owbuild_stage: boot
        owimage:    ${{ parameters.owimage }}
        owtools:    ${{ parameters.owtools }}
    - template: artfsave.yml
      parameters:
        path:       build/$(owobjdir)
        artifname:  build-${{ parameters.arch }}
    - template: artfsave.yml
      parameters:
        path:       bld/watcom/$(owobjdir)
        artifname:  bld-watcom-${{ parameters.arch }}
