parameters:
  arch:     ''
  title:    ''
  owimage:  ''
  owtools:  ''
  owscript: ''

jobs:
  - job: boot${{ parameters.arch }}
    displayName: "${{ parameters.title }}"
    variables:
      owbuild.stage: boot
      owimage:  ${{ parameters.owimage }}
      owtools:  ${{ parameters.owtools }}
    pool:
      vmImage: ${{ parameters.owimage }}
    steps:
    - script: ${{ parameters.owscript }}
      displayName:  "Bootstrap"
    - template: artfsave.yml
      parameters:
        path:       build/$(owobjdir)
        artifname:  build-${{ parameters.arch }}
    - template: artfsave.yml
      parameters:
        path:       bld/watcom/$(owobjdir)
        artifname:  bld-watcom-${{ parameters.arch }}
