parameters:
  arch:     ''
  title:    ''
  image:    ''
  pscript:  ''

jobs:
  - job: boot${{ parameters.arch }}ow
    displayName: "${{ parameters.title }}"
    pool:
      vmImage: ${{ parameters.image }}
    steps:
    - script: ${{ parameters.pscript }}
      displayName: "Bootstrap OW"
