parameters:
  arch:     ''
  title:    ''

jobs:
  - job: boot${{ parameters.arch }}
    displayName: "${{ parameters.title }}"
    variables:
      ${{ if eq(parameters.arch, 'lnx') }}:
        owtools:      $(owtools_lnx)
        owscript:     $(owscript_lnx)
      ${{ if eq(parameters.arch, 'nt') }}:
        owtools:      $(owtools_nt)
        owscript:     $(owscript_nt)
      ${{ if eq(parameters.arch, 'osx') }}:
        owtools:      $(owtools_osx)
        owscript:     $(owscript_osx)
      ${{ if eq(parameters.arch, 'lnxow') }}:
        owtools:      $(owtools_lnxow)
        owscript:     $(owscript_lnx)
        watcom:       $(owwatcom_root_lnx)
        watcom.path:  $(owwatcom_path_lnx)
        watcom.include: $(owwatcom_include_lnx)
      ${{ if eq(parameters.arch, 'ntow') }}:
        owtools:      $(owtools_ntow)
        owscript:     $(owscript_nt)
        watcom:       $(owwatcom_root_nt)
        watcom.path:  $(owwatcom_path_nt)
        watcom.include: $(owwatcom_include_nt)
      owbuild.stage:    boot
    pool:
      ${{ if in(parameters.arch, 'lnx', 'lnxow') }}:
        vmImage: $(owimage_lnx)
      ${{ if in(parameters.arch, 'nt', 'ntow') }}:
        vmImage: $(owimage_nt)
      ${{ if eq(parameters.arch, 'osx') }}:
        vmImage: $(owimage_osx)
    steps:
    - ${{ if eq(parameters.arch, 'ntow') }}:
      - script: echo "##vso[task.setvariable variable=PATH]$(watcom.path);%PATH%"
        displayName: "Set PATH"
    - script: $(owscript)
      displayName: "Bootstrap"
    - template: artfsave.yml
      parameters: 
        arch:       ${{ parameters.arch }}
        ${{ if eq(parameters.arch, 'nt') }}:
          path:     build\$(owobjdir)
        ${{ if in(parameters.arch, 'lnx', 'osx') }}:
          path:     build/$(owobjdir)
        artifname:  build-${{ parameters.arch }}
    - template: artfsave.yml
      parameters: 
        arch:       ${{ parameters.arch }}
        ${{ if eq(parameters.arch, 'nt') }}:
          path:     bld\watcom\$(owobjdir)
        ${{ if in(parameters.arch, 'lnx', 'osx') }}:
          path:     bld/watcom/$(owobjdir)
        artifname:  bld-watcom-${{ parameters.arch }}
