parameters:
  arch:     ''
  title:    ''
  owimage:  ''
  owtools:  ''
  owscript: ''

jobs:
  - job: boot${{ parameters.arch }}ow
    displayName: "${{ parameters.title }}"
    variables:
      ${{ if eq(parameters.arch, 'lnx') }}:
        watcom:       $(owciroot_lnx)/ow
        include:      $(watcom)/lh
        watcom.path:  $(watcom)/binl
      ${{ if eq(parameters.arch, 'nt') }}:
        watcom:       $(owciroot_nt)\ow
        include:      $(watcom)\h;$(watcom)\h\nt
        watcom.path:  $(watcom)\binnt
    pool:
      vmImage: ${{ parameters.owimage }}
    steps:
    - script: ${{ parameters.owscript }}
      displayName: "Bootstrap OW"
      env:
        owbuild_stage:  boot
        owimage:    ${{ parameters.owimage }}
        owtools:    ${{ parameters.owtools }}
