parameters:
  arch:     ''
  title:    ''
  image:    ''
  tools:    ''
  pscript:  ''

jobs:
  - job: boot${{ parameters.arch }}ow
    displayName: "${{ parameters.title }}"
    variables:
      owbuild.stage: boot
      owimage:  ${{ parameters.image }}
      owtools:  ${{ parameters.tools }}
      #
      ${{ if eq(parameters.arch, 'lnx') }}:
        watcom:       $(owciroot_lnx)/ow
        include:      $(watcom)/lh
        watcom.path:  $(watcom)/binl
      ${{ if eq(parameters.arch, 'nt') }}:
        watcom:       $(owciroot_nt)\ow
        include:      $(watcom)\h;$(watcom)\h\nt
        watcom.path:  $(watcom)\binnt
    pool:
      vmImage: ${{ parameters.image }}
    steps:
    - script: ${{ parameters.pscript }}
      displayName: "Bootstrap OW"
