parameters:
  arch:     ''
  title:    ''
  owimage:  ''
  owtools:  ''
  owscript: ''

jobs:
  - job: build${{ parameters.arch }}
    displayName: "${{ parameters.title }}"
    #variables:
    pool:
      vmImage: ${{ parameters.owimage }}
    timeoutInMinutes: 120
    steps:
    - template: dosbox.yml
      parameters:
        arch: ${{ parameters.arch }}
    - template: artfload.yml
      parameters:
        path:       build/$(owobjdir)
        artifname:  build-${{ parameters.arch }}
    - template: artfload.yml
      parameters:
        path:       bld/watcom/$(owobjdir)
        artifname:  bld-watcom-${{ parameters.arch }}
    - script: ${{ parameters.owscript }}
      displayName: "Build"
      env:
        OWBUILD_STAGE: build
        OWIMAGE:    ${{ parameters.owimage }}
        OWTOOLS:    ${{ parameters.owtools }}
    - ${{ if in(parameters.arch, 'lnx', 'nt') }}:
      - template: artfsave.yml
        parameters:
          path:         rel
          artifname:    rel-${{ parameters.arch }}
      - template: artfsave.yml
        parameters:
          path:         bld/setupgui
          artifname:    bld-setupgui-${{ parameters.arch }}
