parameters:
  arch:     ''
  image:    ''
  tools:    ''
  pscript:  ''

jobs:
      - template: docs.yml
        parameters:
          arch:     ${{ parameters.arch }}
          title:    Documentation Build DOS
          doctarget: docdos
          image:    ${{ parameters.image }}
          tools:    ${{ parameters.tools }}
          pscript:  ${{ parameters.pscript }}
      - template: docs.yml
        parameters:
          arch:     ${{ parameters.arch }}
          title:    Documentation Build CHM
          doctarget: docchm
          image:    ${{ parameters.image }}
          tools:    ${{ parameters.tools }}
          pscript:  ${{ parameters.pscript }}
      - template: docs.yml
        parameters:
          arch:     ${{ parameters.arch }}
          title:    Documentation Build NT
          doctarget: docnt
          image:    ${{ parameters.image }}
          tools:    ${{ parameters.tools }}
          pscript:  ${{ parameters.pscript }}
      - template: docs.yml
        parameters:
          arch:     ${{ parameters.arch }}
          title:    Documentation Build OS2
          doctarget: docos2
          image:    ${{ parameters.image }}
          tools:    ${{ parameters.tools }}
          pscript:  ${{ parameters.pscript }}
      - template: docs.yml
        parameters:
          arch:     ${{ parameters.arch }}
          title:    Documentation Build PDF
          doctarget: docpdf
          image:    ${{ parameters.image }}
          tools:    ${{ parameters.tools }}
          pscript:  ${{ parameters.pscript }}
      - template: docs.yml
        parameters:
          arch:     ${{ parameters.arch }}
          title:    Documentation Build WIN
          doctarget: docwin
          image:    ${{ parameters.image }}
          tools:    ${{ parameters.tools }}
          pscript:  ${{ parameters.pscript }}
