parameters:
  arch:     ''
  owimage:  ''
  owtools:  ''
  owscript: ''

jobs:
      - template: docs.yml
        parameters:
          arch:     ${{ parameters.arch }}
          title:    Documentation Build DOS
          owdoctarget: docdos
          owimage:  ${{ parameters.owimage }}
          owtools:  ${{ parameters.owtools }}
          owscript: ${{ parameters.owscript }}
      - template: docs.yml
        parameters:
          arch:     ${{ parameters.arch }}
          title:    Documentation Build Html
          owdoctarget: docchm
          owimage:  ${{ parameters.owimage }}
          owtools:  ${{ parameters.owtools }}
          owscript: ${{ parameters.owscript }}
      - template: docs.yml
        parameters:
          arch:     ${{ parameters.arch }}
          title:    Documentation Build NT
          owdoctarget: docnt
          owimage:  ${{ parameters.owimage }}
          owtools:  ${{ parameters.owtools }}
          owscript: ${{ parameters.owscript }}
      - template: docs.yml
        parameters:
          arch:     ${{ parameters.arch }}
          title:    Documentation Build OS2
          owdoctarget: docos2
          owimage:  ${{ parameters.owimage }}
          owtools:  ${{ parameters.owtools }}
          owscript: ${{ parameters.owscript }}
      - template: docs.yml
        parameters:
          arch:     ${{ parameters.arch }}
          title:    Documentation Build PDF
          owdoctarget: docpdf
          owimage:  ${{ parameters.owimage }}
          owtools:  ${{ parameters.owtools }}
          owscript: ${{ parameters.owscript }}
      - template: docs.yml
        parameters:
          arch:     ${{ parameters.arch }}
          title:    Documentation Build WIN
          owdoctarget: docwin
          owimage:  ${{ parameters.owimage }}
          owtools:  ${{ parameters.owtools }}
          owscript: ${{ parameters.owscript }}
