parameters:
  arch:     ''
  title:    ''
  doctarget: ''
  image:    ''
  pscript:  ''

jobs:
  - job: docs${{ parameters.doctarget }}
    displayName: "${{ parameters.title }}"
    timeoutInMinutes: 90
    variables:
      owdoctarget:  ${{ parameters.doctarget }}
    pool:
      vmImage: ${{ parameters.image }}
    steps:
    - template: artfload.yml
      parameters:
        path:       build/$(owobjdir)
        artifname:  build-${{ parameters.arch }}
    - script: ${{ parameters.pscript }}
      displayName: "Documentation Build"
    - template: artfsave.yml
      parameters:
        path:       rel
        artifname:  rel-${{ parameters.doctarget }}
