parameters:
  arch:     ''
  title:    ''
  doctype:  ''
  owimage:  ''
  owtools:  ''
  owscript: ''

jobs:
  - job: docs${{ parameters.doctype }}
    displayName: "${{ parameters.title }}"
    timeoutInMinutes: 90
    variables:
      owbuild.stage: docs
      owimage:  ${{ parameters.owimage }}
      owtools:  ${{ parameters.owtools }}
      #
      ${{ if eq(parameters.doctype, 'docdos') }}:
        owdoctarget:    docdos
      ${{ if eq(parameters.doctype, 'dochtml') }}:
        owdoctarget:    dochtmlhelp
      ${{ if eq(parameters.doctype, 'docnt') }}:
        owdoctarget:    docnt
      ${{ if eq(parameters.doctype, 'docos2') }}:
        owdoctarget:    docos2
      ${{ if eq(parameters.doctype, 'docpdf') }}:
        owdoctarget:    docpdf
      ${{ if eq(parameters.doctype, 'docwin') }}:
        owdoctarget:    docwin
    pool:
      vmImage: ${{ parameters.owimage }}
    steps:
    - template: artfload.yml
      parameters:
        path:       build/$(owobjdir)
        artifname:  build-${{ parameters.arch }}
    - script: ${{ parameters.owscript }}
      displayName: "Documentation Build"
    - template: artfsave.yml
      parameters:
        path:       rel
        artifname:  rel-${{ parameters.doctype }}
