parameters:
  arch:     ''
  title:    ''
  doctype:  ''
  owdoctarget: ''
  owimage:  ''
  owtools:  ''
  owscript: ''

jobs:
  - job: docs${{ parameters.doctype }}
    displayName: "${{ parameters.title }}"
    timeoutInMinutes: 90
    variables:
      owbuild.stage: docs
      owimage:  ${{ parameters.owimage }}
      owtools:  ${{ parameters.owtools }}
      owdoctarget:  ${{ parameters.owdoctarget }}
    pool:
      vmImage: ${{ parameters.owimage }}
    steps:
    - template: artfload.yml
      parameters:
        path:       build/$(owobjdir)
        artifname:  build-${{ parameters.arch }}
    - script: ${{ parameters.owscript }}
      displayName: "Documentation Build"
    - template: artfsave.yml
      parameters:
        path:       rel
        artifname:  rel-${{ parameters.doctype }}
