parameters:
  arch:     ''
  title:    ''
  owimage:  ''
  owtools:  ''
  owscript: ''

jobs:
  - job: instal${{ parameters.arch }}
    displayName: "${{ parameters.title }}"
    variables:
      owbuild.stage: inst
      owimage:  ${{ parameters.owimage }}
      owtools:  ${{ parameters.owtools }}
    pool:
      vmImage: ${{ parameters.owimage }}
    steps:
    - template: artfload.yml
      parameters:
        path:       build/$(owobjdir)
        artifname:  build-${{ parameters.arch }}
    - template: artfload.yml
      parameters:
        path:       bld/setupgui
        artifname:  bld-setupgui-nt
    - template: artfload.yml
      parameters:
        path:       bld/setupgui
        artifname:  bld-setupgui-lnx
    # consolidate binaries
    - template: artfload.yml
      parameters:
        path:       rel
        artifname:  rel-nt
    - template: artfload.yml
      parameters:
        path:       rel
        artifname:  rel-lnx
    # consolidate documentation
    - template: artfload.yml
      parameters:
        path:       rel
        artifname:  rel-docdos
    - template: artfload.yml
      parameters:
        path:       rel
        artifname:  rel-dochtml
    - template: artfload.yml
      parameters:
        path:       rel
        artifname:  rel-docnt
    - template: artfload.yml
      parameters:
        path:       rel
        artifname:  rel-docos2
    - template: artfload.yml
      parameters:
        path:       rel
        artifname:  rel-docpdf
    - template: artfload.yml
      parameters:
        path:       rel
        artifname:  rel-docwin
    # run build script
    - script: ${{ parameters.owscript }}
      displayName: "Build Installers"
    # create full binary archive
    - ${{ if eq(parameters.arch, 'lnx') }}:
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(owroot)/rel'
          includeRootFolder: false
          archiveType: 'tar'
          archiveFile: '$(owroot)/distrib/ow/bin/ow-snapshot.tar.gz'
          replaceExistingArchive: true
    # save all artifacts for distribution
    - template: artfsave.yml
      parameters:
        path:       distrib/ow/bin
        artifname:  distrib-${{ parameters.arch }}
