parameters:
  arch:     ''
  title:    ''

jobs:
  - job: mirror
    displayName: "${{ parameters.title }}"
    variables:
      owsfproject:  openwatcom/open-watcom-v2-test
      ${{ if eq(parameters.arch, 'lnx') }}:
        owaskpass:  $(Pipeline.Workspace)/askpass.sh
      ${{ if eq(parameters.arch, 'nt') }}:
        owaskpass:  $(Pipeline.Workspace)\askpass.cmd
    pool:
      ${{ if eq(parameters.arch, 'lnx') }}:
        vmImage: $(owimage_lnx)
      ${{ if eq(parameters.arch, 'nt') }}:
        vmImage: $(owimage_nt)
    steps:
    - template: gituser.yml
    - ${{ if in(parameters.arch, 'lnx', 'osx') }}:
      - script: |
          echo "echo \"\$SSH_PASSWORD\"" > $(owaskpass)
        displayName: "Create askpass file"
      - script: chmod +x $(owaskpass)
        displayName: "Set Executable flag"
    - ${{ if eq(parameters.arch, 'nt') }}:
      - script: |
          echo echo %%SSH_PASSWORD%% > $(owaskpass)
          type $(owaskpass)
        displayName: "Create askpass file"
    - script: git checkout master
      displayName: "GitHub Checkout"
    - script: |
        mkdir ~/.ssh
        ssh-keyscan $(owsfhost) > ~/.ssh/known_hosts
        git remote $(owgitverbose) set-url --push origin ssh://$OWSFUSER@$(owsfhost)/p/$(owsfproject)
        git push $(owgitverbose)
      displayName: "Mirror to SF"
      env:
        SSH_PASSWORD:    $(owsftoken2)
        OWSFUSER:        $(owsftoken1)
        SSH_ASKPASS:     $(owaskpass)
        DISPLAY:         :0
        GIT_SSH_COMMAND: "setsid ssh"
