parameters:
  arch:     ''
  title:    ''
  owimage:  ''
  owtools:  ''
  owscript: ''

jobs:
  - job: tests${{ parameters.arch }}
    displayName: "${{ parameters.title }}"
    #variables:
    pool:
      vmImage: ${{ parameters.owimage }}
    steps:
    - template: artfload.yml
      parameters:
        path:       build/$(owobjdir)
        artifname:  build-${{ parameters.arch }}
