parameters:
  arch:     ''
  title:    ''
  image:    ''
  pscript:  ''

jobs:
  - job: testboot${{ parameters.arch }}
    displayName: "${{ parameters.title }}"
    pool:
      vmImage: ${{ parameters.image }}
    steps:
    - template: artfload.yml
      parameters:
        path:       rel
        artifname:  rel-${{ parameters.arch }}
    - script: ${{ parameters.pscript }}
      displayName: "Test Bootstrap OW"
