parameters:
  arch:     ''
  title:    ''
  image:    ''
  pscript:  ''

jobs:
  - job: tests${{ parameters.arch }}
    displayName: "${{ parameters.title }}"
    pool:
      vmImage:  ${{ parameters.image }}
    steps:
    - template: artfload.yml
      parameters:
        path:       build/$(owobjdir)
        artifname:  build-${{ parameters.arch }}
